#!/bin/bash

# RPM package version
VERSION=`git describe --tags --always`

# Path, where rpm building will take place
RPM_BUILD_DIRECTORY=/tmp/globalregistry_rpmbuild

# Bigcouch release submodule
BIGCOUCH_RELEASE_DIRECTORY=`git rev-parse --show-toplevel`/bigcouchdb

# Onepanel release submodule
ONEPANEL_RELEASE_DIRECTORY=`git rev-parse --show-toplevel`/onepanel/rel_provider/onepanel

##############################
# Exit on any failure
set -e

# Enter script directory
RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
cd $RUNNER_SCRIPT_DIR

# Check if globalregistry_node release exists
if [[ ! -d "../globalregistry" ]]; then
  	echo "Generate a release first."
fi

# Prepare empty build directory
rm -rf $RPM_BUILD_DIRECTORY
mkdir -p $RPM_BUILD_DIRECTORY
cd $RPM_BUILD_DIRECTORY

# Create required directory structure
mkdir -p BUILD RPMS SOURCES SPECS SRPMS tmp

# Copy spec file and set version
cp $RUNNER_SCRIPT_DIR/globalregistry.spec SPECS/
sed -i -e s/"{{version}}"/"$VERSION"/g SPECS/globalregistry.spec

# Attach globalregistry release
mkdir -p $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/globalregistry_node
cp $RUNNER_SCRIPT_DIR/install_rpm $RPM_BUILD_DIRECTORY/SOURCES/globalregistry
cp -R $RUNNER_SCRIPT_DIR/../scripts $RPM_BUILD_DIRECTORY/SOURCES/globalregistry
cp -R $RUNNER_SCRIPT_DIR/../globalregistry/* $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/globalregistry_node

# Attach bigcouch release
mkdir -p $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/database_node
cp -R $BIGCOUCH_RELEASE_DIRECTORY/*  $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/database_node

# Attach onepanel release
mkdir -p $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/onepanel_node
cp -R $ONEPANEL_RELEASE_DIRECTORY/*  $RPM_BUILD_DIRECTORY/SOURCES/globalregistry/files/onepanel_node

cd $RPM_BUILD_DIRECTORY/SOURCES
tar zcf globalregistry.tar.gz globalregistry

# Launch rpmbuild
cd $RPM_BUILD_DIRECTORY
rpmbuild -ba SPECS/globalregistry.spec

# Move created RPM to releases directory
mv -f $RPM_BUILD_DIRECTORY/RPMS/x86_64/* $RUNNER_SCRIPT_DIR/..

# Clean up
rm -rf $RPM_BUILD_DIRECTORY
