#!/bin/bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This script creates RPM package.
## @end
## ===================================================================

VERSION=`git describe --tags --always | tr - .`
BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BUILDDIR=${BASEDIR}/build
DISTRIBUTION=fedora-23-x86_64

mkdir -p ${BUILDDIR}
sed "s/@version@/$VERSION/g" ${BASEDIR}/globalregistry.spec > ${BUILDDIR}/globalregistry.spec


cd ${BUILDDIR}
git clone --depth 1 ssh://git@git.plgrid.pl:7999/vfs/globalregistry.git globalregistry-${VERSION}
cd globalregistry-${VERSION}
git submodule init
git submodule update
${BASEDIR}/../../make.py deps
cd onepanel
git submodule init
git submodule update
${BASEDIR}/../../make.py deps
cd ${BUILDDIR}
tar -czf globalregistry-${VERSION}.tar.gz globalregistry-${VERSION}
rm -rf globalregistry-${VERSION}

${BASEDIR}/../../make.py -i onedata/rpm_builder --group mock --privileged \
                             -s ${BUILDDIR} -c mock --root ${DISTRIBUTION} \
                             --buildsrpm --spec ${BUILDDIR}/globalregistry.spec \
                             --sources ${BUILDDIR}/globalregistry-${VERSION}.tar.gz \
                             --resultdir=${BUILDDIR}

${BASEDIR}/../../make.py -i onedata/rpm_builder --group mock --privileged \
                             -s ${BUILDDIR} -c mock --root ${DISTRIBUTION} \
                             --rebuild ${BUILDDIR}/globalregistry-${VERSION}-*.src.rpm \
                             --resultdir=${BUILDDIR}
