#!/bin/bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This script creates RPM package.
## @end
## ===================================================================

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BASE_DIR=${SCRIPT_DIR}/../..
BUILD_DIR=${SCRIPT_DIR}/build

cd ${BASE_DIR}

REPOSITORY=ssh://git@git.plgrid.pl:7999/vfs/globalregistry.git
BRANCH=`git rev-parse --abbrev-ref HEAD`
PKG_VERSION=`git describe --tags --always | tr - .`
PKG_ID=globalregistry-${PKG_VERSION}
DISTRIBUTION=fedora-23-x86_64

mkdir -p ${BUILD_DIR}
sed "s/@version@/$PKG_VERSION/g" ${SCRIPT_DIR}/globalregistry.spec > ${BUILD_DIR}/globalregistry.spec

cd ${BUILD_DIR}
git clone --depth 1 -b ${BRANCH} ${REPOSITORY} ${PKG_ID}

cd ${BASE_DIR}
./make.py -C ${BUILD_DIR}/${PKG_ID} deps
./make.py -C ${BUILD_DIR}/${PKG_ID}/onepanel deps

cd ${BUILD_DIR}
tar -czf ${PKG_ID}.tar.gz ${PKG_ID}
rm -rf ${PKG_ID}

cd ${BASE_DIR}
./make.py -i onedata/rpm_builder --group mock --privileged \
          -s ${BUILD_DIR} -c mock --root ${DISTRIBUTION} \
          --buildsrpm --spec ${BUILD_DIR}/globalregistry.spec \
          --sources ${PKG_ID}.tar.gz --resultdir=${BUILD_DIR}

./make.py -i onedata/rpm_builder --group mock --privileged \
          -s ${BUILD_DIR} -c mock --root ${DISTRIBUTION} \
          --rebuild ${PKG_ID}-*.src.rpm --resultdir=${BUILD_DIR}
